ControleDeProdutosAula/Controllers/ClienteController.cs
using ControleDeProdutosAula.Models;
using ControleDeProdutosAula.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.ComponentModel.DataAnnotations;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace ControleDeProdutosAula.Controllers
{
	public class ClienteController : Controller
	{
		private IHostingEnvironment Environment;
		public const string SessionKeyUser = "_Usuario";
		public const string SessionKeyEmail = "_Email";
		public const string SessionKeyNivel = "_Nivel";

		private readonly IClienteRepositorio _clienteRepositorio;

		public ClienteController(IClienteRepositorio clienteRepositorio,
			IHostingEnvironment _environment)
		{
			_clienteRepositorio = clienteRepositorio;
			Environment = _environment;
		}

		public async Task<IActionResult> Index()
		{
			List<ClienteModel> clientes = await _clienteRepositorio.BuscarTodos();

			var usuario = HttpContext.Session.GetString(SessionKeyUser);
			if (!usuario.IsNullOrEmpty())
			{
				return await Task.FromResult(View(clientes));
			}
			return await Task.FromResult(RedirectToAction("Index", "Home"));
		}

		public async Task<IActionResult> Criar()
		{
			return await Task.FromResult(View());
		}

		public async Task<IActionResult> Editar(long id)
		{
			ClienteModel cliente = await _clienteRepositorio.ListarPorId(id);

			return await Task.FromResult(View(cliente));
		}

		public async Task<IActionResult> ApagarConfirmacao(long id)
		{
			ClienteModel cliente = await _clienteRepositorio.ListarPorId(id);

			return await Task.FromResult(View(cliente));
		}

		public async Task<IActionResult> AtivarDesativar(long id)
		{
			await _clienteRepositorio.AtivarDesativar(id);

			return await Task.FromResult(RedirectToAction("Index"));
		}

		public async Task<IActionResult> Apagar(long id)
		{
			await _clienteRepositorio.Apagar(id);

			return await Task.FromResult(RedirectToAction("Index"));
		}

		[HttpPost]
		public async Task<IActionResult> Criar(ClienteModel cliente, IFormFile? imagemCarregada)
		{
			ClienteModel model = cliente;

			List<ValidationResult> results = new List<ValidationResult>();
			ValidationContext context = new ValidationContext(model, null, null);

			bool isValid = Validator.TryValidateObject(model, context, results, true);

			if (!isValid)
			{
				foreach (var validationResult in results)
				{
					return View(model);
				}
			}

			model.DataDeRegistro = DateTime.Now;
			model.Ativo = true;

			// Carregamento de imagem
			string wwwPath = this.Environment.WebRootPath;
			string path = Path.Combine(wwwPath, "Uploads");
			if (!Directory.Exists(path))
			{
				Directory.CreateDirectory(path);
			}

			string fileName = "";

			if (imagemCarregada != null)
			{
				fileName = Path.GetFileName(imagemCarregada!.FileName);
			} else
			{
				fileName = "no-image.png";
			}


			var caminhoCompleto = Path.Combine(path, fileName);

			using (FileStream stream = new FileStream(caminhoCompleto, FileMode.Create))
			{
				if (imagemCarregada != null)
				{
					imagemCarregada.CopyTo(stream);
					model.NomeDaFoto = caminhoCompleto;
				}
			}

			model.Foto = Util.ReadFully2(caminhoCompleto);

			await _clienteRepositorio.Adicionar(model);

			return await Task.FromResult(RedirectToAction("Index"));
		}

		[HttpPost]
		public async Task<IActionResult> Alterar(ClienteModel cliente)
		{
			await _clienteRepositorio.Atualizar(cliente);
			return await Task.FromResult(RedirectToAction("Index"));
		}
	}
}

ControleDeProdutosAula/Controllers/ProdutoController.cs
using ControleDeProdutosAula.Models;
using ControleDeProdutosAula.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.ComponentModel.DataAnnotations;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace ControleDeProdutosAula.Controllers
{
	public class ProdutoController : Controller
	{
		private IHostingEnvironment Environment;
		public const string SessionKeyUser = "_Usuario";
		public const string SessionKeyEmail = "_Email";
		public const string SessionKeyNivel = "_Nivel";

		private readonly IProdutoRepositorio _produtoRepositorio;

		public ProdutoController(IProdutoRepositorio produtoRepositorio, IHostingEnvironment _environment)
		{
			_produtoRepositorio = produtoRepositorio;
			Environment = _environment;
		}

		public async Task<IActionResult> Index()
		{
			List<ProdutoModel> produtos = await _produtoRepositorio.BuscarTodos();

			var usuario = HttpContext.Session.GetString(SessionKeyUser);
			if (!usuario.IsNullOrEmpty())
			{
				return await Task.FromResult(View(produtos));
			}
			return await Task.FromResult(RedirectToAction("Index", "Home"));
		}

		public async Task<IActionResult> Criar()
		{
			return await Task.FromResult(View());
		}

		public async Task<IActionResult> Editar(long id)
		{
			ProdutoModel produto = await _produtoRepositorio.ListarPorId(id);

			return await Task.FromResult(View(produto));
		}

		public async Task<IActionResult> ApagarConfirmacao(long id)
		{
			ProdutoModel produto = await _produtoRepositorio.ListarPorId(id);

			return await Task.FromResult(View(produto));
		}

		public async Task<IActionResult> AtivarDesativar(long id)
		{
			await _produtoRepositorio.AtivarDesativar(id);

			return await Task.FromResult(RedirectToAction("Index"));
		}

		public async Task<IActionResult> Apagar(long id)
		{
			await _produtoRepositorio.Apagar(id);

			return await Task.FromResult(RedirectToAction("Index"));
		}

		[HttpPost]
		public async Task<IActionResult> Criar(ProdutoModel produto,
			IFormFile? imagemCarregada)
		{
			ProdutoModel model = produto;

			List<ValidationResult> results = new List<ValidationResult>();
			ValidationContext context = new ValidationContext(model, null, null);

			bool isValid = Validator.TryValidateObject(model, context, results, true);

			if (!isValid)
			{
				foreach (var validationResult in results)
				{
					return View(model);
				}
			}

			if (produto.DataDeValidade < DateTime.Now)
			{
				return View(model);
			}

			model.DataDeRegistro = DateTime.Now;
			model.Ativo = true;

			// Carregamento de imagem
			string wwwPath = this.Environment.WebRootPath;
			string path = Path.Combine(wwwPath, "Uploads");
			if (!Directory.Exists(path))
			{
				Directory.CreateDirectory(path);
			}
			string fileName = "";

			if (imagemCarregada != null)
			{
				fileName = Path.GetFileName(imagemCarregada!.FileName);
			}
			else
			{
				fileName = "no-image.png";
			}

			var caminhoCompleto = Path.Combine(path, fileName);

			using (FileStream stream = new FileStream(caminhoCompleto, FileMode.Create))
			{
				if (imagemCarregada != null)
				{
					imagemCarregada.CopyTo(stream);
					model.NomeDaFoto = caminhoCompleto;
				}
			}

			model.Foto = Util.ReadFully2(caminhoCompleto);

			await _produtoRepositorio.Adicionar(model);

			return await Task.FromResult(RedirectToAction("Index"));
		}

		[HttpPost]
		public async Task<IActionResult> Alterar(ProdutoModel produto)
		{
			await _produtoRepositorio.Atualizar(produto);
			return await Task.FromResult(RedirectToAction("Index"));
		}
	}
}

ControleDeProdutosAula/Views/Shared/_Layout.cshtml
@using ControleDeProdutosAula.Controllers;
@{
	var usuario = Context.Session.GetString(LoginController.SessionKeyUser);
	var idUsuario = Context.Session.GetInt32(LoginController.SessionKeyId);
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Controle de Clientes e Produtos</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ControleDeProdutosAula.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Clientes e Produtos</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<div>
						<ul class="navbar-nav flex-grow-1">
							@if (@usuario != null)
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
								</li>
							}
						</ul>
					</div>
					<div>
						<ul class="navbar-nav flex-grow-1">
							@if (@usuario == null)
							{
								<li class="nav-item">
									<a class="btn btn-success" asp-area="" asp-controller="Login" asp-action="Index">Entrar</a>
								</li>
							}
							else
							{
								<li class="nav-item mr-3">
									<a class="nav-link text-secondary" asp-area="" asp-controller="Login" asp-action="Editar" asp-route-id=@idUsuario>@usuario</a>
								</li>
								<li class="nav-item">
									<a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Sair">Sair</a>
								</li>
							}
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="text-center">
			&copy; 2023 - Controle de <a asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a> - <a asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>